
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cameraiq
    username: enterusername
    password: enterpassword
    driverClassName: org.postgresql.Driver
